const images = [
  {
    productId: "1",
    shopId: "1",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "1",
    shopId: "1",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: 800,
    discountPrice: 200,
  },
  {
    productId: "1",
    shopId: "1",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: 1500,
    discountPrice: 1350,
  },
  {
    productId: "4",
    shopId: "11",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "5",
    shopId: "12",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "6",
    shopId: "13",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "t-shirt",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "7",
    shopId: "14",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "t-shirt",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "8",
    shopId: "15",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "t-shirt",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "9",
    shopId: "4",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw2.jpg",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "t-shirt",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "10",
    shopId: "5",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw3.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "jeans",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "11",
    shopId: "7",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw4.jpg",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "jeans",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "12",
    shopId: "8",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw5.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "jeans",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "13",
    shopId: "1",
    image:
      "https://firebasestorage.googleapis.com/v0/b/signin-d4d32.appspot.com/o/ProductImages%2F276-2764022_naruto-shippuden-new-desktop-wallpaper-naruto-wallpapers-for.jpg?alt=media&token=e218855e-854c-44e9-9da2-f7caa73eae45",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "jeans",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "14",
    shopId: "9",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw3.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "jeans",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
  {
    productId: "15",
    shopId: "10",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw4.jpg",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "jeans",
    featured: "true",
    price: 500,
    discountPrice: 350,
  },
];
export default images;
