const images = [
  {
    productId: "1",
    shopId: "1",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw1.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "4",
    shopId: "11",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw1.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "5",
    shopId: "12",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw1.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "shirt",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "6",
    shopId: "13",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw1.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "t-shirt",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "7",
    shopId: "14",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw1.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "t-shirt",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "8",
    shopId: "15",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw1.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "t-shirt",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "9",
    shopId: "4",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw2.jpg",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "t-shirt",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "10",
    shopId: "5",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw3.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "jeans",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "11",
    shopId: "7",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw4.jpg",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "jeans",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "12",
    shopId: "8",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw5.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "jeans",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "13",
    shopId: "1",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw1.jpg",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "jeans",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "14",
    shopId: "9",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw3.jpg",
    desc: "Silent Waters in the mountains in midst of Himilayas",
    category: "jeans",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
  {
    productId: "15",
    shopId: "10",
    image: "https://cdn.rawgit.com/huijing/filerepo/gh-pages/lw4.jpg",
    desc: "Red fort in India New Delhi is a magnificient masterpeiece of humans",
    category: "jeans",
    featured: "true",
    price: "500",
    discountPrice: "350",
  },
];
export default images;
